import json

paragraphs = [
    'Položili jste si někdy otázku, co kdyby Bilbo Pytlík místo cesty za drakem obýval dům z Lega, navázal vztah se Satanovou dcerou, nebo se – vybaven čelovkou a lubrikačním gelem – vydal do nitra vagíny vlastní přítelkyně, z níž vylézají podivné postavy kostlivců a postaviček s růžky na hlavě? Pokud ano, své odpovědi se možná dozvíte z knih Zbouchnul jsem Satanovu dceru a Strašidelná vagína Carltona Mellicka III.',
    'Postavy obou próz představují tragikomické variace na archetyp pasivního hrdiny. Steve ze Strašidelné vagíny vede zdánlivě spokojený, avšak obsahově vyprázdněný život organizovaný výhradně kolem partnerky Stacy; teprve když z ní během intimního aktu vystoupí kostlivec, je Steve – bez náznaku odporu – přiveden k tomu, aby se na její prosbu ponořil do jejího nitra a odhalil, co se tam skrývá. Obdobnou figurou je Jonathan ze Zbouchnul jsem Satanovu dceru: nezaměstnaný starý mládenec bez životní perspektivy, jenž se před vnějším světem ukrývá za zdmi z kostiček Lega a jehož jediným společenským rituálem jsou piva se sumo zápasníkem – až do chvíle, kdy na jeho práh dorazí Veška, dcera samotného Satana, s tvrzením, že nosí jeho dítě.',
    'Oba protagonisté jsou – aniž by o to stáli – dědici pasivního hrdiny tolkienovského střihu. Stejně jako Bilbo Pytlík se ocitají v roli pozorovatele a nástroje okolních sil spíše než autonomního aktéra vlastního příběhu. Následující analýza se věnuje jejich společným charakterovým rysům, sleduje trajektorii jejich vývoje (nebo naopak stagnace) a na závěr konfrontuje překvapivě odlišná východiska, která oba autoři svým postavám na konci nabízejí.',
    'Carlton Mellick III (*1977) je americký prozaik a nekorunovaný král žánru bizarro fiction. Jeho tvorba staví na vrstvení heterogenních kulturních zdrojů: mytologické archetypy – démoni, mořské panny, humanoidní bytosti obývající dělohu – se v ní střetávají s estetikou béčkového sci-fi, jehož mutanti se superschopnostmi sice vzdáleně připomínají X-Meny, avšak s podstatným rozdílem: u Mellicka se tyto schopnosti přenášejí jako pohlavně přenosné nemoci na neumaštěných swingers párty. Výsledkem je průsečík body-horroru, akční grotesky a bizarní romance prostoupený důslednou filmovostí vyprávění. Erotika přitom nefunguje jako prvoplánový prostředek vzrušení srovnatelný s červenou knihovnou; sex Mellick zobrazuje jako tělesný akt překračování hranic mezi entitami, jež nezřídka přesahují kategorii lidského.',
    'Širšího povědomí se autor dočkal románem Satan Burger (2001), který se stal zakládajícím textem současné bizarro fikce. Ke kultovnímu statutu knihy přispěla i kontroverze z roku 2005, kdy aljašská policie zahájila vyšetřování jejího šíření jako distribuce nevhodného materiálu mladistvým. Soud tyto razie prohlásil za nezákonné, čímž se Satan Burger proměnil v symbol boje za literární svobodu v undergroundové komunitě.',
    'Pasivní hrdina není antihrdina ani zbabělec. Je to figura ukotvená v každodennosti, jejíž síla – a zároveň prokletí – spočívá v tom, že čtenáři říká: jsem úplně stejný jako ty. Na rozdíl od svalnatých protagonistů osmdesátkových akčních filmů neoplývá nadlidskou fyzickou zdatností a nekonečnými zásobníky munice; na rozdíl od antických hrdinů není determinován k souboji s Titány ani předurčen k pádu. Jeho nepřítelem je setrvačnost – vlastní i světa kolem něj.',
    'Přesto každý ze tří zde zkoumaných hrdinů představuje vlastní variantu tohoto archetypu. Bilbo Pytlík je ve své podstatě dokonalý průměrný člověk povýšený na úroveň mýtu: spokojený s tím, co má, podezřívavý ke všemu, co by mohlo narušit jeho rytmus. Kdybychom ho zasadili do české kotliny, jmenoval by se Franta Novák, bydlel by na sídlišti nebo v Horní Dolní, vlastnil věrnostní kartičky do Tesca i Lidlu – a u pokladny by tvrdil, že bodíky nesbírá, jen proto, že je příliš líný kartu vytáhnout.',
    'Jonathan je oproti Bilbovi o stupeň dál na téže škále: tam, kde Bilbo pouze rezignoval na dobrodružství, Jonathan rezignoval na dospělost jako takovou. Jako dítě měl jedinou vášeň – stavebnici Lego – a ta mu zůstala až do zralého věku jako jediná konstanta. Ve svém zoufalství a osamocenosti z ní vybudoval doslova vlastní svět: Lego postel, Lego sprchu, Lego televizi, v níž sleduje Lego verzi Charlieho Sheena v Dva a půl chlapa. Za zdmi tohoto sebevytvořeného úkrytu se schovává před povinnostmi, zodpovědností – a stejně tak před radostmi – dospělého života.',
    'Steve je ze všech tří nejméně definován tím, čím je, a nejvíce tím, čím není. O jeho životě mimo vztah se Stacy prakticky nic nevíme – a to pravděpodobně záměrně, protože žádný takový život neexistuje. Steve je exemplární podpantoflák: Stacy jeho světem není, Stacy jeho svět je. Zatímco ona s ním otevřeně manipuluje a neváhá vystavit jeho život nebezpečí, Steve podléhá bez odporu, protože alternativa – existence bez ní – je pro něj nepředstavitelná.',
    'Jeden z klíčových momentů, se kterými si autor musí u pasivních hrdinů poradit, je jejich reakce na volání po dobrodružství. Tolkien k tomuto momentu přistupuje romanticky – a zároveň s jemnou ironií. Bilbo se na cestu nevydá z vlastního rozhodnutí: Gandalf ho v podstatě podvede, trpaslíci obsadí jeho dům bez pozvání, vyprázdní spižírnu a ráno Bilbo najde na stole dopis, v němž stojí, že je najat jako zlodějíček. Jeho jediná skutečná volba celého prvního dílu nastane až ve chvíli, kdy za odjíždějící družinou v poslední chvíli vyběhne z Dna Pytle – a zapomene kapesník. Je to zároveň jeho první a na dlouhou dobu také poslední okamžik, kdy se zachová jako aktivní hybatel vlastního příběhu.',
    'Mellick ve zbývajících dvou případech přistupuje k témuž momentu výrazně prozaičtěji. Do Jonathanova Lego domu jednoho dne dorazí rohatá žena v posledním trimestru těhotenství s tvrzením, že dítě je jeho. Jonathan slib, který jí dá – že se k němu i s dítětem může nastěhovat – záhy poruší, přestože Veška byla vyhnána z pekla a nemá kam jít. K odpovědnosti ho nepřinutí ani jeho důsledně tradicionalistická rodina: když od matky dostane ultimátum, aby se postaral o ženu, kterou přivedl do jiného stavu, jinak přestane být členem rodiny, Jonathan od nedělní večeře prostě odejde. Na své dobrodružství se vydá teprve tehdy, když ho v baru navštíví Veščina démonická rodina z pekelné strany – a poté, co pobijí téměř všechny přítomné, mu srozumitelně vysvětlí, že si Vešku vezme, ať chce, nebo ne.',
    'Steve se se svým voláním setká při pohlavním styku, když zaslechne podivné zvuky vycházející ze Stacy. Ta ho uklidní: straší jí ve vagíně odmalička, občas se tam ozve hlas, a když byla malá, občas z ní vylezla dívka s růžky, se kterou si pak hrála. Zlom nastane, když ze Stacy vystoupí kostlivec – a to vyděsí i ji samotnou. Kostlivce společně zlikvidují ještě během aktu, ale Stacy to nedá. Rozhodne se zjistit, co se v ní děje, a přesvědčí Steva, aby se do ní vydal: když se tam vejde kostlivec nebo dívka s růžky, proč by se nevešel on. Všichni tři hrdinové tedy vstupují do příběhu stejným způsobem – ne vlastní volbou, ale tlakem okolí. Otázka je, co s tím tlakem udělají.',
    'Všechny tři příběhy se víceméně drží narativního hrdinského schématu a k němu neodmyslitelně patří postava mentora. V případě Hobita jím není nikdo jiný než Gandalf – postava, která se stala synonymem mentorství v poválečné i současné populární kultuře a pro naše účely ji není třeba zvlášť rozebírat. Zajímavější budou Mellickovy variace: Veška a Fig.',
    'Veška splňuje roli mentora jen částečně a svérázně. Do Jonathanovy cesty vstupuje ještě dříve, než kniha začíná – při samotném početí dítěte. Jako sukuba byla vyslána na zem hledat panny a brát jim duše; při své první výpravě narazila na Jonathana, avšak zaklínadlo na odebrání duše se jí nezdařilo a místo toho otěhotněla. Její původní záměr tedy nebyl nijak ušlechtilý. V průběhu příběhu Jonathana provází peklem, vysvětluje mu, jak to doopravdy chodí s náboženstvím, a učí ho kouzla – a tato dvojice svižně posouvá děj dopředu už jen tím, že jsou spolu. Přesto Veška není Gandalfem ani mistrem Yodou. Je to naivní dívka ztracená ve světě lidí i ve svém rodném podsvětí, a tak se z ní stává spíše katalyzátor chaosu a původce problémů než jejich řešitelka.',
    'V případě Fig – dívky s lepkavými růžky – je situace ještě složitější a označení mentor zde možná ani není zcela na místě. Přesto se pokusím obhájit, proč by jím být mohla. Vogler definuje mentora jako postavu, která připravuje hrdinu na to, aby čelil neznámému a přijal dobrodružství – přičemž dodává, že mentorem nemusí být nutně člověk, ale klidně i mapa nebo zkušenost. Fig se ke Stevovi chová přátelsky a není vyloženě zápornou postavou, avšak její motivace je čistě sobecká. Steve se s ní setká během průzkumu Stacyiny dělohy a Fig ho provede tímto světem, který je pro něj potenciálně nebezpečný – obývají ho totiž zefroni, kostlivci vylézající z vagíny. Fig tedy Stevovi poskytuje orientaci v prostoru, do nějž už vstoupil – nikoli průvodce na prahu dobrodružství, ale průvodce uvnitř něj. To z ní dělá mentora pozdního a situačního: ne toho, kdo hrdinu vyšle, ale toho, kdo mu pomůže přežít, kam už dorazil.',
    'Vyjma Kafkovy Proměny prochází každý pasivní hrdina proměnou nebo přímo katarzí. Mohli bychom dále diskutovat, zda taková proměna není podraz na čtenáře, kteří se chtějí zaměřit na život NPC ve velkých příbězích, ale troufnu si tvrdit, že většina čtenářů hledá právě tu transformaci.',
    'Ze tří zkoumaných hrdinů prochází Steve zdánlivě nejmenší proměnou. Fig ho provede světem Stacyiny dělohy a představí ho jeho matce, vzápětí však odhalí svou skutečnou motivaci: chce si se Stevem hrát (myslí tím sex) – a postupně se stává agresivnější, až prohlásí, že si s ním bude hrát navěky, protože to tvrdí její matka. Steve se pokusí utéct a právě zde dochází k paradoxu: na okamžik se stává aktivním hrdinou, který se pokouší prostřílet hordou zefronů. Ve skutečnosti však neutíká od Stacy, nýbrž za ní (technicky vzato z její dělohy). Zefroni ho záhy zajmou a uvrhnou na rozkaz Fig do jámy, kde Steve začíná pomalu přijímat její podobu a stává se stejnou bytostí jako ona. Zatímco živoří v jámě a myslí na Stacy, dozví se přes vysílačku, že ho podvedla a otěhotněla s někým jiným. Oba bývalí partneři se nakonec setkají v děloze tohoto nového dítěte, kde si vše v klidu vyříkají a v dobrém se rozejdou. Steve se následně zamiluje do Fig. Jde o progres? Těžko říct – Steve jen vymění jednu ženu, kolem které organizoval celý svůj život, za druhou. Strukturálně se nezměnilo nic.',
    'Nejvýraznější proměnou prošel Jonathan – a zároveň nejproblematičtější. Zlom přichází při návštěvě Veščiny pekelné rodiny, kdy ho nastávající tchýně vezme stranou a vysvětlí mu, že Veška není pro peklo stavěna. Jonathanovi v tu chvíli dojde, že ji miluje a že by se o ni měl postarat. Je to jeden z mála upřímně dojemných momentů celé knihy – a Mellick ho bohužel záhy pohřbí pod lavinou přehnaného vývoje: Jonathan se nejprve s nožem postaví vlastní rodině, aby Vešku ochránil, a kniha vyvrcholí scénou, v níž vede pekelný batalion proti náboženské sektě s Lego rotačním kulometem v ruce. Závěr působí – a je možné, že záměrně – jako parodie amerického béčkového akčňáku. Stejně trapně rychlá je i Jonathanova vnitřní proměna: nesebevědomý samotář se během několika stránek promění v Terminátora, který své rodině odpustí pokus o vlastní vraždu s lehkostí, jež by záviděl i Steven Seagal.',
    'Srovnání tří hrdinů v závěru odhaluje tři různé odpovědi na tutéž otázku. Bilbova proměna je ze všech tří nejautentičtější – není náhlá ani groteskní, ale postupná a nenápadná. Přesto ani on není prost rozporů: v bitvě pěti armád, tedy v okamžiku největší zkoušky, se schová s prstenem moci. Tolkien tím naznačuje, že pasivní hrdina může dozrát, aniž by přestal být sám sebou – a že to není slabost, ale svého druhu integrita.',
    'Jonathan prošel proměnou nejviditelnější a zároveň nejpochybnější. Z nesebevědomého samotáře se stal strojem na zabíjení – ale bez procesu, který by takovou změnu ospravedlnil. Mellick tím možná záměrně paroduje konvenci, podle níž musí pasivní hrdina na konci příběhu nutně jednat. Steve neprošel proměnou žádnou. Ze závislosti na jedné osobě se dostal do závislosti na osobě druhé. Jeho cesta skončila tam, kde začala – jen s jinou adresou.',
    'Zdroje:',
    'MELLICK III, Carlton. Zbouchnul jsem Satanovu dceru. Praha: Carcosa, 2019. ISBN 978-80-88244-09-7.',
    'MELLICK III, Carlton. Strašidelná vagína. Praha: Carcosa, 2018. ISBN 978-80-88244-03-5.',
    'TOLKIEN, J. R. R. Hobit aneb Cesta tam a zase zpátky. Praha: Argo, 2012. ISBN 978-80-257-0741-8.',
    'CAMPBELL, Joseph. Tisíc tváří hrdiny. Praha: Portál, 2000. VOGLER, Christopher. The Writer’s Journey. Studio City: Michael Wiese Productions, 2007.',
]

content = {
    "kapitoly": [{
        "nazev": "",
        "ilustrace": "",
        "basne": [{"nazev": "", "isPoetry": False, "sloky": [{"verse": [p]} for p in paragraphs]}]
    }]
}

with open('Hobit_content.json', 'w', encoding='utf-8') as f:
    json.dump(content, f, ensure_ascii=False, indent=2)

config = {
    "document": {
        "title": "Hobit aneb cesta do strašidelné vagíny",
        "author": "Mirek Mrkvička",
        "isbn": "",
        "colophon": {},
        "pages_to_generate": 50
    },
    "layout": {
        "page_size": "110x180",
        "width_pt": 311.811, "height_pt": 510.236,
        "margins_pt": {"top": 50, "bottom": 50, "inner": 65, "outer": 45},
        "units": "pt",
        "chapter_own_page": False,
        "chapter_illustration": False
    },
    "styles": {
        "chapter_title": {"font": "Courier Prime", "size": 20, "alignment": "center", "space_before": 40, "space_after": 30},
        "poem_title": {"font": "Courier Prime", "size": 16, "alignment": "left", "space_before": 20, "space_after": 23},
        "verse": {"font": "Courier Prime", "size": 9, "alignment": "left", "line_spacing": 15, "space_after_stanza": 8},
        "toc_title": {"font": "Courier Prime", "size": 14, "alignment": "left"},
        "toc_item": {"font": "Courier Prime", "size": 11, "alignment": "left"},
        "page_number": {"font": "Courier Prime", "size": 9, "alignment": "center"}
    }
}

with open('export_config_hobit.json', 'w', encoding='utf-8') as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print(f'Hotovo: {len(paragraphs)} odstavcu')
